### PR TITLE
Unify dtypes in numpy array

### PR DESCRIPTION
**Pull request by swmoon-unist**
dtype=int             =>    dtype=np.int32
dtype=float          =>    dtype=np.float64
dtype=complex   =>    dtype=np.complex128

### CODE REVIEW

**Comment by jkha-unist** [comment]
Seems fine.

**Comment by inseonglee** [comment]
For extract_QM method (see line 241 of ./src/qm/qchem/dft.py), there exists a part to convert string to array using np.array and astype method.
These two lines can be combined by using dtype.

force = np.array(force); force = force.astype(float) -> force = np.array(force, dtype=np.float64)

How about changing these parts in this PR?

**Comment by DaehoHan** [comment]
> For extract_QM method (see line 241 of ./src/qm/qchem/dft.py), there exists a part to convert string to array using np.array and astype method.
> These two lines can be combined by using dtype.
> 
> force = np.array(force); force = force.astype(float) -> force = np.array(force, dtype=np.float64)
> 
> How about changing these parts in this PR?

**Comment by DaehoHan** [comment]
@inseonglee Sounds good.

**Comment by tikimtikim** [comment]
> For extract_QM method (see line 241 of ./src/qm/qchem/dft.py), there exists a part to convert string to array using np.array and astype method.
> These two lines can be combined by using dtype.
> 
> force = np.array(force); force = force.astype(float) -> force = np.array(force, dtype=np.float64)
> 
> How about changing these parts in this PR?

agree

**Comment by jkha-unist** [comment]
> > For extract_QM method (see line 241 of ./src/qm/qchem/dft.py), there exists a part to convert string to array using np.array and astype method.
> > These two lines can be combined by using dtype.
> > force = np.array(force); force = force.astype(float) -> force = np.array(force, dtype=np.float64)
> > How about changing these parts in this PR?
> 
> agree

seconded

**Comment by inseonglee** [comment]
good.

**Comment by jkha-unist** [comment]
fine

**Pull request merged**
