### PR TITLE
Add options for auxiliary trajectory violating the total energy conservation.

### PR DESCRIPTION
**Pull request by jkha-unist**

### CODE REVIEW

**Comment by DaehoHan** [comment]
Good.

**Comment by tikimtikim** [comment]
Good

**Comment by jkha-unist** [comment]
manual

**Comment by DaehoHan** [comment]
Comment for the aux_econs_viol argument of the SHXF class is missing.

**Comment by inseonglee** [comment]
대호 comment 대로 class 밑의 설명만 한줄 추가해주면 될 듯.

**Comment by swmoon-unist** [comment]
LGTM

**Pull request merged**
