### PR TITLE
Add exponential propagator and library file

### PR DESCRIPTION
**Pull request by sjkim-unist**
- [x] add exponential propagator file (src/mqc/el_prop/exponential.c)
- [x] change el_propagator.pyx and mqc.py to use exponential propagator and to show error message.
- [x] add setup_expon.py to use library(I think it will be combined or renamed setup.py)
- [x] add library folder and file (src/lib/liblapack.a)

NEED your Opinion
- [ ] Combine setup.py and setup_expon.py
- [ ] variable name
- [x] change error message(when we use exponential with density) and remove comment about exponential with density

### CODE REVIEW

**Comment by sjkim-unist** [comment]
Screenshot from 2022-03-31 19-24-58

**Comment by sjkim-unist** [comment]
[setup_py_problem.pptx](https://github.com/skmin-lab/unixmd/files/8425459/setup_py_problem.pptx)

**Comment by sjkim-unist** [comment]
When we run this code using exponential progapator without linking to math library, we will get an error message from C due to the absence of functions(zheev, zgemm).
pyunix
I think the error message should be rasied using "ValueError" of Python.
The optimal solution to this problem would be raising the "ValueError" during python initialization.
A solution I am thinking of is reading setup.py during the initialization step.

**Comment by sjkim-unist** [comment]
https://github.com/sjkim-unist/unixmd/tree/exponential_propagator_add

**Comment by skmin-lab** [comment]
modified request merged in #225

**Pull request closed without merging**
